---
- name: ensure openssl-devel present
  yum: name=openssl-devel state=present

- name: ensure sqlite-devel present
  yum: name=sqlite-devel state=present
  when: env == 'vagrant'

- name: download {{ executable_python }} source
  get_url:
    url: http://python.org/ftp/python/{{ py_version }}/Python-{{ py_version }}.tar.xz
    dest: /tmp/Python-{{ py_version }}.tar.xz
    timeout: 30
  when: python_check|failed

- name: unpack {{ executable_python }} source
  unarchive:
    src: /tmp/Python-{{ py_version }}.tar.xz
    dest: /tmp
    copy: no
  when: python_check|failed

- name: install {{ executable_python }} from source
  shell: ./configure --prefix=/usr/local && make && make altinstall
  args:
    chdir: /tmp/Python-{{ py_version }}
  when: python_check|failed

- name: create symlink in /usr/bin
  alternatives:
    name: "{{ executable_python }}"
    link: /usr/bin/{{ executable_python }}
    path: /usr/local/bin/{{ executable_python }}
  when: python_check|failed

- name: download pip install script
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
    timeout: 30
  when: easy_install_check|failed

- name: install pip, setuptools, and wheel
  command: "/usr/bin/{{ executable_python }} get-pip.py"
  args: { chdir: /tmp }
  when: easy_install_check|failed or pip_check|failed
